# Generated by Django 4.0.5 on 2022-06-22 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_options_post_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
